registry-srv:
  image: registry:2
  ports:
    - 127.0.0.1:5000:5000
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  volumes:
    - ./data:/data

registry-web:
  image: hyper/docker-registry-web
  ports:
    - 127.0.0.1:8080:8080
  environment:
    REGISTRY_URL: http://registry-srv:5000/v2
    REGISTRY_NAME: localhost:5000 hyper/docker-registry-web
  links:
    - registry-srv
